/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static boolean validateBrackets(String str){
        if((str.contains("(") && str.contains(")")) || (str.contains("{") && str.contains("}")) || (str.contains("[") && str.contains("]"))){
            return true ;
        }else{
            return false;

        }

    }

    public static void main(String[] args) throws Exception {

       Stack s=new Stack();
       s.push(1);
       s.push(2);
       int s2=s.pop();
        System.out.println(s2);
        s.push(5);
        System.out.println(s.peek());
        System.out.println(s.isEmpty());

        Queue q1=new Queue();
        q1.enqueue(1);
        q1.enqueue(2);
        q1.enqueue(3);
        System.out.println(q1.toString());
        System.out.println(q1.dequeue());
        System.out.println(q1.toString());
        System.out.println(q1.isEmpty());
        Queue q2=new Queue();
        System.out.println(q2.isEmpty());
        PseudoQueue ps1=new PseudoQueue();
        ps1.enqueue(1);
        ps1.enqueue(2);
        ps1.enqueue(3);
        ps1.enqueue(4);
        int l=ps1.dequeue();
        System.out.println(ps1.toString());

        System.out.println(validateBrackets("(]("));
        System.out.println(validateBrackets("()[[Extra Characters]]"));


    }
}
