/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

       LinkedList ls=new LinkedList();
        System.out.println(ls.tostring());
        ls.insert(1);
        System.out.println(ls.tostring());
        ls.insert(2);
        System.out.println(ls.tostring());
        ls.insert(23);
        System.out.println(ls.tostring());
        System.out.println("is the list include 23 ?"+ls.includes(23));
        System.out.println("is the list include 1 ?"+ls.includes(1));
        System.out.println("is the list include 0 ?"+ls.includes(0));



    }
}
