/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fibonacci;

public class App {
    static int fib(int n)
    {
        /* Declare an array to store Fibonacci numbers. */
        int fibonacci[] = new int[n+2]; // 1 extra to handle case, n = 0
        /* 0th and 1st number of the series are 0 and 1*/
        fibonacci[0] = 0;
        fibonacci[1] = 1;
        for (int i = 2; i <= n; i++)
        {
       /* Add the previous 2 numbers in the series
         and store it */
            fibonacci[i] = fibonacci[i-1] + fibonacci[i-2];
        }

        return fibonacci[n];
    }
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        int n =4;
        System.out.println(fib(n));
    }
}
