/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void instantiateEmptyLinkedList(){
        LinkedList ls= new LinkedList();
        assertEquals(null,ls.head,"the head should be empty");
    }
    @Test void insertTest(){
        LinkedList ls= new LinkedList();
        ls.insert(1);
        assertEquals(1,ls.length,"the linked list should have length equle to number of item we inserted");

    }
    @Test void TestHead(){
        LinkedList ls= new LinkedList();
        ls.insert(1);
        ls.insert(2);
        ls.insert(3);
        assertEquals(1,ls.head.value,"the head sould be node 1");

    }
    @Test void insertMultiple(){
        LinkedList ls = new LinkedList();
        ls.insert(1);
        ls.insert(3);
        ls.insert(2);
        assertEquals(3,ls.length,"the linked list should have length equle to number of item we inserted");

    }
    @Test void testIncludes(){
        LinkedList ls = new LinkedList();
        ls.insert(1);
        ls.insert(3);
        ls.insert(2);
        assertEquals(true,ls.includes(3),"number 3 is exists should return true");
        assertEquals(false,ls.includes(0),"number 0 is not exists should return false");

    }
    @Test void tostringTest(){
        LinkedList ls = new LinkedList();
        ls.insert(1);
        ls.insert(3);
        ls.insert(23);
        assertEquals("{ 1 } ->{ 3 } ->{ 23 } ->NULL",ls.tostring(),"should return the list ");
    }

}
