/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge.sort;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void mergeSort(int arr[]){
      if(arr.length >1){
          int mid=arr.length/2;
          int[] left=new int[mid] ;
          int [] right=new int[arr.length-mid];
          for (int i=0;i<mid ;i++){
              left[i]=arr[i];
          }
          for(int i=0 ;i<arr.length-mid;i++){
              right[i]=arr[i+mid];
          }
          mergeSort(left);
          mergeSort(right);
          merge(left,right,arr);
      }
    }
    public static void merge(int left[],int right[],int arr[]){
        int i=0,j=0,k =0;
        while (i<left.length && j<right.length){
            if(left[i]<=right[j]){
                arr[k]=left[i];
                i++;
            }
            else {
                arr[k]=right[j];
                j++;
            }
            k++;
        }
        //copy remaining element
        while (i<left.length){
            arr[k]=left[i];
            i++;
            k++;
        }
        while (j<right.length){
            arr[k]=right[j];
            j++;
            k++;
        }
    }
    public static void main(String[] args) {
    int arr[]={8,4,23,42,16,15};
    mergeSort(arr);
    for(int i=0;i<arr.length;i++)
        System.out.println(arr[i]);

    }
}
