/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge.sort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void testMergeSort(){
        int arr[]={8,4,23,42,16,15};
        App.mergeSort(arr);

        int res[]={4,8,15,16,23,42};
        assertArrayEquals(res,arr);
    }

}
