/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertion.sort;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void insertionSort(int arr[])
    {

        for (int i = 1; i < arr.length; ++i) {
            int key = arr[i];
            int j = i - 1;
            while (j >= 0 && arr[j] > key) {
                arr[j + 1] = arr[j];
                j = j - 1;
            }
            arr[j + 1] = key;
        }
    }

    public static void main(String[] args) {
        int arr[]= {8, 4, 23, 42, 16, 15};
        insertionSort(arr);
        for(int i=0 ;i<arr.length;i++){
            System.out.println(arr[i]);
        }
    }
}
