/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge;

import java.util.ArrayList;

public class App {


    public static void main(String[] args) {

    BinarySearchTree b1=new BinarySearchTree();
    b1.Add(23);
    b1.Add(42);
    b1.Add(85);
    b1.Add(8);
    b1.Add(16);
        ArrayList <Integer> ls=new ArrayList<>();
        ls=b1.DFTpre(b1.root);
        System.out.println("pre order");
        ls.forEach((n) -> System.out.println(n));
       ArrayList <Integer> ls2=new ArrayList<>();
       ls2=b1.DFTIn(b1.root);
        System.out.println("IN order");
        ls2.forEach((n) -> System.out.println(n));
        ArrayList <Integer> ls3=new ArrayList<>();
        ls3=b1.DFTPost(b1.root);
        System.out.println("post order");
        ls3.forEach((n) -> System.out.println(n));

        System.out.println("is the tree contain 16 ? "+b1.contains(16));
        System.out.println("is the tree contain 9 ? "+b1.contains(9));
        System.out.println("the max number is " + b1.maximumValue());


    }
}
