/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;

import java.util.HashSet;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void testRepeatedWord(){
        String test1 = "Once upon a time, there was a brave princess who...";
        String test2="It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...";
        String test3="It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
        assertEquals("a",App.repeatedWord(test1));
        assertEquals("it",App.repeatedWord(test2));
        assertEquals("summer",App.repeatedWord(test3));
    }
    @Test void testTreeIntersection(){
        BinarySearchTree b1=new BinarySearchTree();
        b1.Add(150);
        b1.Add(250);
        b1.Add(350);
        b1.Add(500);
        b1.Add(200);
        b1.Add(300);

        b1.Add(160);
        b1.Add(125);

        b1.Add(175);
        b1.Add(100);

        b1.Add(75);
        BinarySearchTree b2=new BinarySearchTree();
        b2.Add(42);
        b2.Add(600);

        b2.Add(350);
        b2.Add(500);

        b2.Add(100);
        b2.Add(15);

        b2.Add(160);
        b2.Add(175);

        b2.Add(125);
        b2.Add(200);
        b2.Add(5);

        Set<Integer>set= new HashSet<>();
        set.add(160);
        set.add(100);
        set.add(500);
        set.add(200);
        set.add(125);
        set.add(350);
        set.add(175);
        assertArrayEquals(set.toArray(),App.treeIntersection(b1,b2).toArray());
    }
}
